version: '3.6'
services:
  dart-server:
    build: ./sample_api/
    ports:
      - "3000:3000"
      
  postgres-sample:
    image: postgres:12
    restart: always
    ports:
    - "5555:5432"
    volumes:
    - ./sample_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: usuario123
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: sample

  postgres-hasura:
    image: postgres:12
    restart: always
    volumes:
    - ./hasura_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v2.9.0
    ports:
    - "8888:8080"
    depends_on:
    - "postgres-hasura"
    - "postgres-sample"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres-hasura:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://usuario123:senha123@postgres-sample:5432/sample
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: Senha123
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "06c219e5bc8378f3a8a3f83b4b7e4649"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: unauthorized
