name: sample_api
description: A sample api to use with Hasura.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  shelf: ^1.3.2
  shelf_modular: ^2.0.1
  hasura_connect: ^4.0.0+4
  corsac_jwt: ^1.0.0-nullsafety.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
